//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        public int ID_Benutzer { get; set; }
        public int ID_Object { get; set; }
        public string Rolle { get; set; }
        public string Email { get; set; }
        public string Passwort { get; set; }
        public string Telefon { get; set; }
    }
}
