//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenutzerRollen
    {
        public int Id { get; set; }
        public Nullable<int> BenutzerId { get; set; }
        public Nullable<int> RollenId { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Rollen Rollen { get; set; }
    }
}
