//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisziplinenAuswahl_Beschreibung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisziplinenAuswahl_Beschreibung()
        {
            this.KategorienDisziplinen = new HashSet<KategorienDisziplinen>();
            this.Disziplinen = new HashSet<Disziplinen>();
        }
    
        public int Index { get; set; }
        public Nullable<int> Wettkampfart_Index { get; set; }
        public Nullable<double> Anzahl_Auswahlmöglichkeit { get; set; }
        public Nullable<double> Anzahl_Auszuwählen { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<System.DateTime> Erstellt_am { get; set; }
        public string Erstellt_von { get; set; }
        public Nullable<System.DateTime> Letzte_Änderung { get; set; }
        public string Zuletzt_gespeichert { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Wettkampfart Wettkampfart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KategorienDisziplinen> KategorienDisziplinen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disziplinen> Disziplinen { get; set; }
    }
}
