//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disziplin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disziplin()
        {
            this.Wahldisziplin = new HashSet<Wahldisziplin>();
            this.Kategore_Disziplin = new HashSet<Kategore_Disziplin>();
        }
    
        public int ID_Disziplin { get; set; }
        public int ID_Wettkampf { get; set; }
        public string Name { get; set; }
        public string Abkuerzung { get; set; }
        public Nullable<short> ZeitTeilnehmer { get; set; }
        public int AnzahlVersuche { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wahldisziplin> Wahldisziplin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategore_Disziplin> Kategore_Disziplin { get; set; }
        public virtual Wahldisziplin Wahldisziplin1 { get; set; }
        public virtual Wettkampf Wettkampf { get; set; }
    }
}
