//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disziplinen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disziplinen()
        {
            this.KategorienDisziplinen = new HashSet<KategorienDisziplinen>();
        }
    
        public int Id { get; set; }
        public string Disziplin { get; set; }
        public string Abkuerzung { get; set; }
        public int WettkampfartId { get; set; }
        public Nullable<int> anzTeilnehmer { get; set; }
        public Nullable<int> Versuche { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KategorienDisziplinen> KategorienDisziplinen { get; set; }
        public virtual Wettkampfart Wettkampfart { get; set; }
    }
}
