//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategorienDisziplinen
    {
        public int Id { get; set; }
        public int KategorieId { get; set; }
        public int DisziplinId { get; set; }
    
        public virtual Disziplinen Disziplinen { get; set; }
        public virtual Kategorien Kategorien { get; set; }
    }
}
