//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategorienDisziplinen
    {
        public int Index_Kategorien { get; set; }
        public int Index_DisziplinenAuswahl_Beschreibung { get; set; }
    
        public virtual DisziplinenAuswahl_Beschreibung DisziplinenAuswahl_Beschreibung { get; set; }
    }
}
