//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategorie()
        {
            this.Kategore_Disziplin = new HashSet<Kategore_Disziplin>();
        }
    
        public int ID_Kategorie { get; set; }
        public int ID_Wettkampf { get; set; }
        public string Name { get; set; }
        public string Abkuerzung { get; set; }
        public string Geschlecht { get; set; }
        public short JahrgangVon { get; set; }
        public short JahrgangBis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategore_Disziplin> Kategore_Disziplin { get; set; }
        public virtual Wettkampf Wettkampf { get; set; }
    }
}
