//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Startnummer
    {
        public int ID_Startnummer { get; set; }
        public int ID_Wettkampf { get; set; }
        public int ID_Athlet { get; set; }
        public int ID_Verein { get; set; }
        public int Startnr { get; set; }
    
        public virtual Athlet Athlet { get; set; }
        public virtual Wettkampf Wettkampf { get; set; }
    }
}
