//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Startnummern
    {
        public int Id { get; set; }
        public int WettkampfId { get; set; }
        public int AthletId { get; set; }
        public int Startnummer { get; set; }
    
        public virtual Athleten Athleten { get; set; }
        public virtual Wettkampf Wettkampf { get; set; }
    }
}
