//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teilnehmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teilnehmer()
        {
            this.Teilnehmer_Leistung = new HashSet<Teilnehmer_Leistung>();
        }
    
        public int Index { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Jahrgang { get; set; }
        public int Kategorie { get; set; }
        public int Verein { get; set; }
        public string Auszeichnung { get; set; }
        public Nullable<double> Rang { get; set; }
        public string Bemerkung { get; set; }
        public string DisziplinenListe { get; set; }
        public string GesamtPunktZahl { get; set; }
        public Nullable<bool> Gast { get; set; }
        public Nullable<bool> Mutation { get; set; }
        public Nullable<int> Mutationsgrund { get; set; }
        public Nullable<System.DateTime> MutationsDatum { get; set; }
        public string SonstigerMutationsgrund { get; set; }
        public Nullable<System.DateTime> Erstellt_am { get; set; }
        public string Erstellt_von { get; set; }
        public Nullable<System.DateTime> Letzte_Änderung { get; set; }
        public string Zuletzt_gespeichert { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string Email { get; set; }
    
        public virtual Verein Verein1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teilnehmer_Leistung> Teilnehmer_Leistung { get; set; }
    }
}
