//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teilnehmer_Leistung
    {
        public int Index { get; set; }
        public int Index_Teilnehmer { get; set; }
        public int Index_Disziplin { get; set; }
        public string Leistung { get; set; }
        public string Punkte { get; set; }
        public Nullable<bool> Unfall { get; set; }
        public Nullable<bool> Nicht_Gestartet { get; set; }
        public string Eintrag { get; set; }
        public Nullable<int> IndexDisziplinenAuswahl { get; set; }
        public Nullable<System.DateTime> Erstellt_am { get; set; }
        public string Erstellt_von { get; set; }
        public Nullable<System.DateTime> Letzte_Änderung { get; set; }
        public string Zuletzt_gespeichert { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Disziplinen Disziplinen { get; set; }
        public virtual Teilnehmer Teilnehmer { get; set; }
    }
}
