//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RLP2000_Gruppe5Entities : DbContext
    {
        public RLP2000_Gruppe5Entities()
            : base("name=RLP2000_Gruppe5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bewertungsart> Bewertungsart { get; set; }
        public virtual DbSet<Disziplinen> Disziplinen { get; set; }
        public virtual DbSet<DisziplinenAuswahl_Beschreibung> DisziplinenAuswahl_Beschreibung { get; set; }
        public virtual DbSet<Geschlechter> Geschlechter { get; set; }
        public virtual DbSet<KategorienDisziplinen> KategorienDisziplinen { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teilnehmer> Teilnehmer { get; set; }
        public virtual DbSet<Teilnehmer_Leistung> Teilnehmer_Leistung { get; set; }
        public virtual DbSet<Verein> Verein { get; set; }
        public virtual DbSet<Wettkampfart> Wettkampfart { get; set; }
        public virtual DbSet<Kategorien> Kategorien { get; set; }
    }
}
