//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verein
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Verein()
        {
            this.Benutzer = new HashSet<Benutzer>();
            this.Teilnehmer = new HashSet<Teilnehmer>();
            this.VereineWettkampf = new HashSet<VereineWettkampf>();
        }
    
        public int Index { get; set; }
        public string Vereinsname { get; set; }
        public string PC_Konto { get; set; }
        public string Bank_Konto { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Strasse { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Telefon_privat { get; set; }
        public string Telefon_geschäft { get; set; }
        public string FAX { get; set; }
        public string Natel { get; set; }
        public string E_Mail { get; set; }
        public Nullable<System.DateTime> Erstellt_am { get; set; }
        public string Erstellt_von { get; set; }
        public Nullable<System.DateTime> Letzte_Änderung { get; set; }
        public string Zuletzt_gespeichert { get; set; }
        public string ImportDatei { get; set; }
        public string ExportDatei { get; set; }
        public string Vorrunde { get; set; }
        public Nullable<int> IndexVereinVorrunde { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Benutzer> Benutzer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teilnehmer> Teilnehmer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VereineWettkampf> VereineWettkampf { get; set; }
    }
}
