//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vereinsverantwortlicher
    {
        public int ID_Vereinsverantwortlicher { get; set; }
        public int ID_Verein { get; set; }
        public int ID_Adresse { get; set; }
        public string Mailadresse { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
    
        public virtual Verein Verein { get; set; }
        public virtual Adresse Adresse { get; set; }
    }
}
