//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VereineWettkampf
    {
        public int Id { get; set; }
        public int VereinId { get; set; }
        public int WettkampfId { get; set; }
    
        public virtual Verein Verein { get; set; }
        public virtual Wettkampf Wettkampf { get; set; }
    }
}
