//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wahldisziplin
    {
        public int ID_Wahldisziplin_Disziplin { get; set; }
        public int ID_Wahldisziplin { get; set; }
        public int ID_Disziplin { get; set; }
    
        public virtual Disziplin Disziplin { get; set; }
        public virtual Disziplin Disziplin1 { get; set; }
    }
}
