//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournevent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wettkampf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wettkampf()
        {
            this.Anmeldung = new HashSet<Anmeldung>();
            this.Disziplin = new HashSet<Disziplin>();
            this.Kategorie = new HashSet<Kategorie>();
            this.Startnummer = new HashSet<Startnummer>();
        }
    
        public int ID_Wettkampf { get; set; }
        public int ID_Administrator { get; set; }
        public string Name { get; set; }
        public System.DateTime Datum { get; set; }
        public System.DateTime Teilnahmebeginn { get; set; }
        public System.DateTime Teilnahmeschluss { get; set; }
        public int NummerVon { get; set; }
        public int NummerBis { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anmeldung> Anmeldung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disziplin> Disziplin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategorie> Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Startnummer> Startnummer { get; set; }
    }
}
